---
# file: tasks/ruby.yml
# playbook to install ruby packages

- name: Ensure all dependencies are present
  apt:
    name: build-essential
    state: present

- name: Ensure ruby packages are present
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ reddit_ruby_packages }}"

- name: Ensure bundler package is present
  gem:
    name: bundler
    user_install: no
    state: present
