---
# file: main.yml

- hosts: all
  gather_facts: yes
  become: yes

  vars_files:
    - vars.yml

  tasks:

    - include: tasks/ruby.yml
      tags: ruby

    - include: tasks/mongodb.yml
      tags: mongodb
  handlers:

    - name: reload mongod
      service:
        name: mongod
        state: restarted
