---
# file: main.yml

- hosts: all
  gather_facts: yes
  become: yes

  vars_files:
    - vars.yml

  tasks:

    - include: tasks/ruby.yml
      tags: ruby

    - include: tasks/mongodb.yml
      tags: mongodb

    - include: tasks/deploy.yml
      tags: deploy

  handlers:

    - name: reload mongod
      service:
        name: mongod
        state: restarted

    - name: reload puma
      systemd:
        state: restarted
        daemon_reload: yes
        name: puma
