---

- hosts: tag_db
  gather_facts: false
  become: true

  pre_tasks:
    - name: Ensure python 2.7 is present
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: output
      changed_when:
        - output.stdout != ""
        - output.stdout != "\r\n"
    - name: Gather facts
      setup:

  roles:
    - ansible-role-mongodb
